# 导入antigen.zsh，antigen.zsh是一个管理zsh插件的工具
source ~/.antigen.zsh
# 使用使用 oh-my-zsh 作为默认的插件和主题源
# 相比于加载 oh-my-zsh 中的大量默认插件，你可以仅加载所需的插件，这会减少启动时间
antigen use oh-my-zsh

# 添加要使用的插件，可以在ohmyzsh项目plugins文件夹下找到
# 当你尝试运行一个未安装的命令时，它会提示你应该安装哪个包来提供该命令
antigen bundle command-not-found
# 自动补全插件，扩充zsh的自动补全功能
antigen bundle zsh-users/zsh-completions
# 当你输入一个命令时，它会在你的历史记录中搜索匹配的命令进行建议
antigen bundle zsh-users/zsh-autosuggestions
# 设置主题，主题可以在ohmyzsh项目themes下找到
antigen theme robbyrussell

# 最后必须提交确认修改
antigen apply

# smart cd function, allows switching to /etc when running 'cd /etc/fstab'
function cd () {
    if (( ${#argv} == 1 )) && [[ -f ${1} ]]; then
        [[ ! -e ${1:h} ]] && return 1
        print "Correcting ${1} to ${1:h}"
        builtin cd ${1:h}
    else
        builtin cd "$@"
    fi
}

# 为了与bash兼容
setopt no_nomatch
# 禁用rm，使用trash-cli代替
# alias rm='echo "Please use trash-cli instead."; false'
# 终端支持256色
# export TERM=xterm-256color
# 始终带有颜色的grep（默认情况下，grep不会在管道中使用颜色）
alias grepc='grep --color=always'
# 始终带有颜色的ls
alias lsc='ls --color'
# 始终带有颜色的rg
alias rgc='rg --color=always'
# 始终带有颜色的ag
alias agc='ag --color'
# 为bat设置别名
alias bat='batcat'
# 设置bat忽略大小写
export BAT_PAGER="less -RFi"
