# antigen配置, 用于管理zsh插件
# 导入antigen.zsh
source ~/.antigen.zsh
# 使用使用 oh-my-zsh 作为默认的插件和主题源
# 相比于加载 oh-my-zsh 中的大量默认插件，你可以仅加载所需的插件，这会减少启动时间
antigen use oh-my-zsh

# 添加要使用的插件，可以在ohmyzsh项目plugins文件夹下找到
# 当你尝试运行一个未安装的命令时，它会提示你应该安装哪个包来提供该命令
antigen bundle command-not-found
# 自动补全插件，扩充zsh的自动补全功能
antigen bundle zsh-users/zsh-completions
# 当你输入一个命令时，它会在你的历史记录中搜索匹配的命令进行建议
antigen bundle zsh-users/zsh-autosuggestions
# 设置主题，主题可以在ohmyzsh项目themes下找到
# gnzh, fishy, gallifrey 也不错
antigen theme lukerandall

# 最后必须提交确认修改
antigen apply

# 一些软件会放置在~/.local/bin下，需要将其加入PATH
export PATH="$HOME/.local/bin:$PATH"

# 与bash兼容
setopt no_nomatch
# 禁用rm，使用trash-cli代替
# alias rm='echo "Please use trash-cli instead."; false'
# 终端支持256色
# export TERM=xterm-256color

# 给命令设置别名
alias fd='fdfind'
alias bat='batcat'

# 自定义函数
# 如果cd的参数是一个文件，那么自动切换到该文件所在的目录
cd () {
    if (( ${#argv} == 1 )) && [[ -f ${1} ]]; then
        [[ ! -e ${1:h} ]] && return 1
        print "Correcting ${1} to ${1:h}"
        builtin cd ${1:h}
    else
        builtin cd "$@"
    fi
}
lsc () {
    ls -ahl --color "$@" | batcat
}
rgc() {
    rg -iu. --color=always "$@" 2>/dev/null | batcat
}
agc() {
    ag --color "$@" 2>/dev/null | batcat
}
fdc() {
    fdfind --color=always -HI "$@" 2>/dev/null | batcat
}
treec() {
    tree -C "$@" 2>/dev/null | batcat
}

# bat相关配置
# 设置bat忽略大小写
export BAT_PAGER="less -RFi"
# 设置bat主题
export BAT_THEME="Coldark-Dark"

# 显示欢迎界面
clear
cat ~/.welcome

